import {
  MdStore,
  MdRestaurantMenu,
  MdShoppingCart,
  MdWhatsapp,
  MdDeliveryDining,
  MdPayments,
  MdAccessTime,
  MdLocationOn,
  MdPhone,
  MdLogout,
  MdDashboard,
  MdPeople,
  MdCampaign,
  MdSettings,
  MdClose,
  MdAdd,
  MdRemove,
  MdDelete,
  MdCheck,
  MdEdit,
  MdVisibility,
  MdVisibilityOff,
  MdSearch,
  MdFilterList,
  MdSort,
  MdArrowBack,
  MdArrowForward,
  MdKeyboardArrowDown,
  MdKeyboardArrowUp,
  MdInfo,
  MdWarning,
  MdError,
  MdFavorite,
  MdFavoriteBorder,
  MdStar,
  MdStarBorder,
  MdHome,
  MdMenu,
  MdMoreVert,
  MdRefresh,
  MdSend,
  MdImage,
  MdUpload,
  MdCategory,
  MdReceipt,
  MdCalendarToday,
  MdTimer,
  MdPerson,
  MdAssignment,
  MdDoneAll,
  MdCancel,
  MdSchedule,
  MdTrendingUp,
  MdInventory2,
} from 'react-icons/md'

export const Icons = {
  // Navigation
  home: MdHome,
  menu: MdMenu,
  restaurantMenu: MdRestaurantMenu,
  dashboard: MdDashboard,
  orders: MdReceipt,
  customers: MdPeople,
  broadcast: MdCampaign,
  settings: MdSettings,
  back: MdArrowBack,
  forward: MdArrowForward,
  more: MdMoreVert,

  // Actions
  cart: MdShoppingCart,
  whatsapp: MdWhatsapp,
  add: MdAdd,
  remove: MdRemove,
  delete: MdDelete,
  edit: MdEdit,
  close: MdClose,
  check: MdCheck,
  send: MdSend,
  refresh: MdRefresh,
  upload: MdUpload,
  search: MdSearch,
  filter: MdFilterList,
  sort: MdSort,
  logout: MdLogout,

  // Status
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
  done: MdDoneAll,
  cancel: MdCancel,
  pending: MdSchedule,

  // Food & Business
  store: MdStore,
  delivery: MdDeliveryDining,
  payment: MdPayments,
  time: MdAccessTime,
  location: MdLocationOn,
  phone: MdPhone,
  category: MdCategory,
  image: MdImage,
  inventory: MdInventory2,
  receipt: MdReceipt,

  // Users
  person: MdPerson,
  people: MdPeople,

  // Misc
  favorite: MdFavorite,
  favoriteBorder: MdFavoriteBorder,
  star: MdStar,
  starBorder: MdStarBorder,
  trendingUp: MdTrendingUp,
  calendar: MdCalendarToday,
  timer: MdTimer,
  assignment: MdAssignment,
  visibility: MdVisibility,
  visibilityOff: MdVisibilityOff,
  arrowDown: MdKeyboardArrowDown,
  arrowUp: MdKeyboardArrowUp,
}

export type IconName = keyof typeof Icons

export function Icon({ name, className = '', size = 24 }: { name: IconName; className?: string; size?: number }) {
  const Component = Icons[name]
  return <Component className={`inline-block ${className}`} size={size} />
}

export const categoryIcons: Record<string, string> = {
  pollos: '🍗',
  hamburguesas: '🍔',
  tacos: '🌮',
  guarniciones: '🧆',
  bebidas: '🥤',
  postres: '🍰',
}
